name: sample-workflow

on:
  pull_request_target:
    types:
      - opened
    branches:
      - main
    paths:
      - '**.yml'
    

jobs:
  sample-issue-workflow:
    name: Issue Creation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x Part 1
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Set up Python 3.x Part 2
        run: |
          # set up python requirements and scripts
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..

      - name: Sample Issue
        id: sample_issue
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          ve1/bin/python3 scripts/library.py --pr_url="${{ github.event.pull_request._links.self.href }}" --branch="${{github.head_ref}}" --src_repo="${{github.event.pull_request.head.repo.full_name}}"
